parameters:
  version: ""
  display_version: ""

jobs:
  - job: verify_${{ parameters.display_version }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      displayName: "prepare python"
      inputs:
        versionSpec: '${{ parameters.version }}'
        addToPath: true
        architecture: 'x64'
    - script: |
        python -m pip install flake8
        flake8 pdchaoskit/
      displayName: 'static code analysis'
    - script: |
        python -m pip install -r requirements.txt -r requirements-dev.txt
        python -m pytest
      displayName: 'test'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'tests/.results/junit-test-results.xml'
      displayName: 'publish test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'tests/.results/coverage.xml'
      displayName: 'publish coverage results'